### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by habernal** [Unbabel/MAIA#1]
Dear all,

The license paragaph is contradicting itself:

> MAIA corpus is released under the Creative Commons public license Attribution-NoDerivatives 4.0 International ([CC BY-ND 4.0](https://creativecommons.org/licenses/by-nc/4.0)) and can be freely used for research purposes only. Please note that, as the license states, no commercial uses are permitted for this corpus.

The link points to "CC BY-NC 4.0" (not CC BY-ND 4.0) which is "Attribution-NonCommercial 4.0 International". It restricts commercial use.

In contrast, CC BY-ND 4.0 ("Attribution-NoDerivatives 4.0 International") ( https://creativecommons.org/licenses/by-nd/4.0/ ) **does not** restrict commercial use.

I believe what you wanted was CC BY-N**C** 4.0, not CC BY-N**D** 4.0.

**Comment by afarajian** [comment]
Dear Ivan,

thank you for noticing it and reporting it to us. Indeed, it was supposed to be CC BY-NC 4.0 (Attribution-NonCommercial 4.0 International) as it was in abbreviation and the link to the license. I just fixed the issue and updated the readme file.

**Comment by afarajian** [comment]
Dear Ivan,

thank you for noticing it and reporting it to us. Indeed, it was supposed to be CC BY-NC 4.0 (Attribution-NonCommercial 4.0 International) as it was in abbreviation and the link to the license. I just fixed the issue and updated the readme file.
